[build]
  publish = "dist"
  command = "npm run build"

# SEE https://www.netlify.com/docs/redirects/
# rewrite from /pagename to /pagename.html is done automatically
# fallback to 404.html is done automatically
